### ISSUE TITLE
Issue with BS_ALLOW_MEMCPY_SERIALIZATION/memcpy

### ISSUE THREAD

**Issue by nemerle** [GameFoundry/bsf#104]
According to [cppreference](http://en.cppreference.com/w/cpp/types/is_trivially_copyable)
"Objects of trivially-copyable types are the only C++ objects that may be safely copied with std::memcpy "

Sadly some of bsf's types using BS_ALLOW_MEMCPY_SERIALIZATION are not trivially-copyable according to gcc >= 6.1  i.e `static_assert (std::is_trivially_copyable<AABox>()==true,"AABox is trivial")` this fails.

Types I've identified as not-trivially-copyable so far:
* Vector2
* Vector3
* Vector3I
* Vector4
* Vector4I
* AABox
Additionally Vector2I is missing `BS_ALLOW_MEMCPY_SERIALIZATION` and is still memcp'ied
by `copyParamLookup[GPDT_INT2] = &copyParam<Vector2I>;`

The fixes would look like this https://github.com/nemerle/bsf/compare/master...nemerle:gcc_8_1_fixes?expand=1

**Comment by jonesmz** [comment]
The changes in your branch look great so far.

For this line:

std::is_trivially_copyable<type>()==true,#type "is not trivially copyable");

Would you consider breaking it into two lines to keep the "\" characters aligned? Just a personal style thing, i don't really care much either way.

and I think you need a space between the quote and "is", don't you?

**Comment by nemerle** [comment]
Yup will fix this in the actual PR + I think You've meant aligning the \\ chars ? :grin: 
Still I'm going to wait for @BearishSun to chime in on this, since I've removed explicit assignment operators, and the Banshee3D's c# scripting might not like that  ?

**Comment by jonesmz** [comment]
*sigh* Github keeps dropping characters from things I say. Yep, i meant the \ chars. Apparently github decided that I wanted some weird formatting behavior.

Cool, of course it's his project, I'm just a guy from the peanut gallery.

**Comment by BearishSun** [comment]
Looks great. It won't break scripting as those simple types are fully implemented in their parent language (for performance, to avoid interop method calls for every simple operation, and due to the fact script binding generator would need to be a bit more advanced to fully convert C++ to C#).

Indeed `Vector2I` should also have a `BS_ALLOW_MEMCPY_SERIALIZATION` but just to make it clear, the macro doesn't really care or prevent the use of `memcpy` on the type (which is what I believe `copyParam<Vector2I>` does). It's only relevant for serialization methods like `rttiWriteElem`, `rttiReadElem` and higher level forms of serialization (`IReflectable` and `RTTIType`).

The only thing I'd change is the use of list initializers vs constructors in `Vector3`. However unlikely this may be in the case of `Vector3`, I don't like the idea of being reliant on the order of fields in a class. It's more of a general concern than one for `Vector3`, but I like consistency. It would be easy for someone to rearrange class fields and as long as the types match, the code might break in a very silent way. I think programmers are a bit more wary when changing constructor parameters. Unless you believe there is a benefit to list initializers that outweighs these concerns.

**Comment by nemerle** [comment]
Well, since the static_assert is there, adding BS_ALLOW_MEMCPY_SERIALIZATION will also check if the memcpy usage on the type is kosher :smile: 

And those Vector3 -> {} replacements were done during the beginning of the hunt for the proper resolution to memcpy warnings, I've reverted all of those calls in the latest commit to this branch.

So, do You prefer a squashed commit for this branch, or should I PR this as is ?

**Comment by BearishSun** [comment]
Ah, indeed! Nice.

Squashed commit sounds better but I don't care much either way.

**Comment by nemerle** [comment]
Closing this since PR has been made :smile:
