### ISSUE TITLE
Pasting over selected text does not work as expected in GUIInputBox

### ISSUE THREAD

**Issue by jayrulez** [GameFoundry/bsf#117]
Pasting over selected text does not work as expected because the control loses focus when an item from the context menu is selected.

I can look into this further but I believe the issue occurs because the container with the cut/copy/paste options gains focus causing the underlying GUIInputBox to lose focus (which clears the selected text internally).

**Comment by BearishSun** [comment]
Thanks for the report. I've submitted a fix da5b6fca29edf144aa426311b29f588a72a56f87. 

You are right about the problem being focus loss. I've modified the code for pasting so it works the same as cut/copy, which simply read the selection range regardless if the selection is shown or not. This works because when clearing selection range (during focus loss), only visuals are cleared and the range is kept. 

If you have a more elegant solution let me know. One option might be to add the ability for a GUI element to "lock" focus while its context menu is open. That would be handled by the GUIManager which could avoid sending focus loss event to a locked control.
