### ISSUE TITLE
Various questions

### ISSUE THREAD

**Issue by jonesmz** [GameFoundry/bsf#141]
One of the people contributing to that Open Space Program game that I mentioned in other issues here on github has raised some questions about the Banshee / BSF development plans.

Note that I haven't tried to search for answers to these questions myself yet. Just acting as a middleman.

* Are there any plans to provide a Bullet Physics plugin?
* Are there any plans to provide some kind of physics timewarp feature? He noted that the physics FPS seems to be hardcoded at 60 fps.
* Is there a way to directly modify meshes? The person looking into that came to the conclusion that things were pretty hardcoded. This is related to the creation of round planets from far away all the way to directly on the surface. This is the comparable source code from Urho3d, I think: https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Graphics/CustomGeometry.h 
* Plans for physics state interpolation? I'm not entirely certain what that's supposed to be, but apparently Godot doesn't do it, and Urho3d does.
* Also, could you speak to the PhysX code around line 500 of https://github.com/GameFoundry/bsf/blob/master/Source/Plugins/bsfPhysX/BsPhysX.cpp which fetches the results immediately? Is that something that could be a template or runtime parameter?
* There were also some concerns about this warning on the readme : WARNING: Banshee is still in development and should not be used in production. With the upcoming 1.0 release, will this no longer be a concern?

**Comment by BearishSun** [comment]
- _Are there any plans to provide a Bullet Physics plugin?_

No such plans at the moment I'm afraid.
- _Are there any plans to provide some kind of physics timewarp feature? He noted that the physics FPS seems to be hardcoded at 60 fps._

You can change the hardcoded FPS value to anything you like, or change it dynamically if needed. I don't have plans on adding a timewarp feature but I believe it should just be a matter adding a scaling factor to the time-delta sent to `Physics::fixedUpdate` (perhaps combined with increasing the physics FPS in order to improve stability/precision). If you decide to add this stuff I'd be happy to integrate it into the core.
- _Is there a way to directly modify meshes? The person looking into that came to the conclusion that things were pretty hardcoded. This is related to the creation of round planets from far away all the way to directly on the surface. This is the comparable source code from Urho3d, I think: https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Graphics/CustomGeometry.h_

You can modify meshes in all sorts of ways. https://www.bsframework.io/docs/creating_meshes.html being the most straightforward approach.

You can also use the low-level rendering API and write to vertex/index buffers directly. Vulkan backend also offers support for upload queues, so you can make sure GPU doesn't block rendering while you're uploading dynamic data.

- _Plans for physics state interpolation? I'm not entirely certain what that's supposed to be, but apparently Godot doesn't do it, and Urho3d does._

If physics runs at 60 FPS, but game refreshes at 140, interpolation updates the physical object movement for the in-between frames. And yes this is planned, but I don't have a clear timeframe when. It probably wouldn't be too hard to implement by modifying `PhysX::fixedUpdate`, running a step ahead, storing the previous step then just interpolating between the two.

- _Also, could you speak to the PhysX code around line 500 of https://github.com/GameFoundry/bsf/blob/master/Source/Plugins/bsfPhysX/BsPhysX.cpp which fetches the results immediately? Is that something that could be a template or runtime parameter?_

Could you elaborate? I'm not sure which code this is referring to, nor what exactly is meant by the question.

- _There were also some concerns about this warning on the readme : WARNING: Banshee is still in development and should not be used in production. With the upcoming 1.0 release, will this no longer be a concern?_

`bsf` itself is fairly stable, and any remaining issues should be easily fixable, so I can recommend it for production use. 

Banshee editor is certainly less stable and I still wouldn't recommend it for production use.

I don't expect any major problems, but there certainly will be problems, which will be a hassle unless you are willing to dig into C++ to resolve them, or wait on me to do it. Next release for Banshee will probably not be 1.0 but rather 0.5 - which will include a lot of fixes, polish and quality of life improvements, but will quite likely still not be quite there yet.

**Comment by BearishSun** [comment]
Gonna close this for now. If there are further questions please ask on https://discourse.bsframework.io as I'll keep the issue tracker reserved for bugs and features only, thanks!
