### ISSUE TITLE
A few questions about PrefabDiffs and their future directions

### ISSUE THREAD

**Issue by nemerle** [GameFoundry/bsf#161]
1. Are prefab diffs applied recursively ?
Say, I have a `Prefab` A that contains a `Prefab` B, apply a diff to prefab A node that modifies some component X, will component X in some node of Prefab B also be modified ?

2. Are there any plans for 'selective' PrefabDiffs ?
For example, I have a prefab of a building, but want to replace **all** "MetalRoof" textures/materials with "RustedMetalRoof", right now it does not look like there is any way of doing that

**Comment by BearishSun** [comment]
1. No. `PrefabDiff`s only contain information about a single prefab and don't contain other prefab instances. It doesn't make sense internally since child prefab instances can change independantly of their parent.

2. You shouldn't need to use `PrefabDiff`s for that. The idea behind `Prefab`s is to have a single `Prefab` to act as a blueprint, and you instantiate other objects from that blueprint. When you need to change something you need to edit the original `Prefab` with required changes (in your case changing the texture), and then call `PrefabUtility::updateFromPrefab()`. This method can be called on individual prefab instances, or entire scenes and it will automatically update any prefab instances in the provided hierarchy with the changes you have made to the blueprint.

`PrefabDiff` was created primarily for cases where you want a specific instance to differ from the blueprint (e.g. you want one instance to have a different texture that won't get overriden when the blueprint prefab changes during `PrefabUtility::updateFromPrefab()`). This type of change can be recorded by modifying the instance and then calling `PrefabUtility::recordPrefabDiff()`. If you ever need to revert a prefab instance to the original state of its blueprint then call `PrefabUtility::revertToPrefab`.

**Comment by BearishSun** [comment]
Closing this. If you have further questions please open up a thread on discourse.bsframework.io as I'm trying to move all questions there.
