### ISSUE TITLE
Problem with basic shadow setups with radial or spot light

### ISSUE THREAD

**Issue by ivalduan** [GameFoundry/bsf#168]
I attach a scene as simplified as possible to reproduce.
https://drive.google.com/open?id=12ylmbXk5nnsNKbXgBfZJULdqU0dHHk-E

The only light type that casts shadows correctly in the scene is directional.
Tested with Windows and DirectX11/Vulkan APIs.

Also sometimes a spot light appears and disappears from view moving inside a scene, so there seems to be a problem with the visibility of this type of light, I will try to reproduce in another example.

**Comment by ivalduan** [comment]
It seems that (opt.intersects(bounds)) fails inside ShadowRenderQueue::execute even if a cube or a sphere are inside the light volume, the plane casts shadows correctly on the cube.
bounds is good so it has to be opt frustum planes.

**Comment by BearishSun** [comment]
Thanks for the report. I'll take a closer look later, but since you seem to be investigating, take a look at PR #165 . It changed the order of frustum planes in a convex volume which could have possibly affected the bounds tests. It's a longshot but its the only thing in that system that has been recently changed. I'll dig deeper when I get a chance.

**Comment by w-flo** [comment]
Sorry about that, I should have done a better job checking this when suggesting to change the plane ordering. The collection itself is only used for iteration, but of course that changes the insertion order for other collections, even including CCamera::getWorldFrustum(), and I failed to take that into account. Maybe issue #169 is related? Should PR #165 be reverted / changed to restore the old plane ordering, in order to prevent any further surprises? Scanning the various files I can't find any other obvious dependency on plane order, but it's a risk.

**Comment by BearishSun** [comment]
When you made that PR I vaguely remembered there was a plane ordering bit of code within the shadow rendering code that could be affected, but I couldn't find it either. No need to revert the PR as I'm pretty sure the ordering is not relevant elsewhere. (But if we had the ordering in the first place this issue wouldn't have happened as I would have used the enum instead of referencing the far plane in this way :) ).

Issue #169 doesn't appear to be related, it seems to be just an issue with spot light bound calculation.
