### ISSUE TITLE
ImGui Integration

### ISSUE THREAD

**Issue by King-Aardvark** [GameFoundry/bsf#189]
I am wondering what would be the best way to integrate [ImGui](https://github.com/ocornut/imgui) with bsf.

I managed to hack together bsf and the ImGui glfw_opengl3 example, but it launches a separate window that is not rendered by bsf. 

Solving this requires custom render bindings. I followed [this](https://github.com/ocornut/imgui/blob/06e917f135672ec998206f56e18a3fecc9d24834/imgui.cpp#L161) and wasn't sure how to proceed with the MyImGuiRenderFunction() function. To support DirectX, Opengl, and Vulkan would I have to create separate bindings for each bsf render plugin apis? 

[Here](https://github.com/ocornut/imgui/blob/06e917f135672ec998206f56e18a3fecc9d24834/examples/imgui_impl_opengl3.cpp#L124) is a non-pseudocode example of MyImGuiRenderFunction().

I was also wondering what would be the cleanest approach to integrating with bsf. Currently I am wrapping the ImGui code around [CoreApplication::runMainLoop()](https://github.com/GameFoundry/bsf/blob/555463c2bfe9180189372102f20afb614f5d34ee/Source/Foundation/bsfCore/BsCoreApplication.cpp#L178). Should it be thrown into BsfApplication or even it's own plugin?

**Comment by BearishSun** [comment]
Could we move this to discourse.bsframework.io please?

I'm not familiar enough with ImGui to give you a specific answer, but bsf comes with low level rendering API you can use for interacting with DirectX/OpenGL/Vulkan transparently (no need to interact with specific plugins). You'll want to get ImGui to use those, as well as potentially accept a window handle that was created in bsf.

bsf does rendering on a separate thread, so that might be an issue, although you can still queue low level rendering commands from the main thread, it's just not going to be the most performant solution.

**Comment by BearishSun** [comment]
Closing this and we can move to the discourse if further discussion is required.
