### ISSUE TITLE
PhysicsMesh (Triangle) does not seem to work correctly after loading

### ISSUE THREAD

**Issue by ataulien** [GameFoundry/bsf#287]
I have a scene where I load a triangle mesh which is used for rendering and collision via the triangle PhysicsMesh. Additionally, I insert the FPS-Walker and FPS-Camera from the examples which makes me able to move around.

This all works if I construct the scene from scratch. After that construction is done, I then save the scene so it can be loaded faster next time, which works fine except for the physics part as it seems.

On the initial load, the character drops a few meters and stops at what seems to be characters height. I can then move around normally.

On the second load (from the saved prefab), the character will drop further down, just so that the camera is right above the ground. If I then press one of the movement-keys, the character drops through the ground. 

The character and the camera aren't saved with the scene. They get inserted after the prefab was loaded and instantiated.

@BearishSun Not sure how to describe the issue further... If you have an idea and want me to try something I'll be glad to do so.

**Comment by BearishSun** [comment]
The mesh collider in question is the one you're walking on (and fall through?).

>On the initial load, the character drops a few meters and stops at what seems to be characters height. I can then move around normally.
This is without the save prefab right. This describes normal behavior?

Can you try loading from the saved prefab, but then manually load the mesh and assign it to the mesh collider. Does that work? Just trying to isolate the issue to the mesh collider.

I'm currently in the middle of some networking changes so I might not be able to take a closer look for a few days, but I'm guessing I'll be able to reproduce the issue myself when I do. If you have a project you can share in a .zip (something I can quickly compile with no additional fuss) it could help me figure it out sooner.

**Comment by ataulien** [comment]
> The mesh collider in question is the one you're walking on (and fall through?).

Yes, out of all physics related things I have only that collider and the character controller in my scene.

> This is without the saved prefab right. This describes normal behavior, right?

Correct, everything works when the scene was not loaded via prefab. However, right now I am not instantiating the prefab on the first run but rather use the created scene-object directly. 
I'm going to see what happens if I just instantiate the prefab after creating it rather than using the original scene object.

> Can you try loading from the saved prefab, but then manually load the mesh and assign it to the mesh collider. Does that work? Just trying to isolate the issue to the mesh collider.

Good idea, I will try that.

**Comment by BearishSun** [comment]
Turns out I'm unable to reproduce this after all. I'm able to save the scene containing a mesh collider, and on the following runs it instantiates correctly with the collider in place.

Let me know if you can provide exact code, and perhaps even the exact mesh to reproduce the issue.

Also, make sure you are saving & loading the resource manifest correctly. If you are not then the system will be unable to find any resources during scene load. I assumed this wasn't a case for you as you mentioned the rest of the scene loads correctly, but I guess it could be possible in case you aren't referencing any other resources.

**Comment by ataulien** [comment]
Hmm, thanks for trying. I will see if I can put together a minimal example. 

I'm using the cached mesh data from an other mesh to initialize the physics mesh. Maybe that is the problem?

**Comment by BearishSun** [comment]
It's possible, but I feel it's unlikely. `MeshData` is just a bunch of vertices and indices, no matter where from you get it, so it /should/ behave the same.

**Comment by ataulien** [comment]
Turns out `PhysicsMesh` is a resource that you need to save. If I do that, everything works fine.

However, a debug-info about the broken resource reference would have been nice to have. Shouldn't be there a warning of some sort if a resource cannot be found?

**Comment by BearishSun** [comment]
I agree it would be nice to report these situations but it's hard to distinguish between a broken reference and a resource that just hasn't been loaded yet - because that's a valid situation as well, user could decide to load the resource later, or it might be queued for async load. I don't have a clear idea yet how to distinguish from these situations.
