### ISSUE TITLE
Engine Editor based Qt framework and bsf

### ISSUE THREAD

**Issue by cylof22** [GameFoundry/bsf#390]
How to integrate the QtMainWindow with bsf framework?

**Comment by hhyyrylainen** [comment]
Seems like no one is responding to this, so I'll share my observation. It's not possible to run bsf so that bsf is not in control of the main loop (which is probably required for use with any full GUI solution). I had to copy-paste a lot of the code from bs application in order to make a function that renders a single frame. I'm trying to get together a draft pull request for seeing how external main loop functionality could be added to bsf. Anyway, the answer to your question is that, you have to figure it out yourself, and it's likely going to be quite tricky.

**Comment by BearishSun** [comment]
Please post questions on discourse.bsframework.io.
